//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Attuned {
            get {
                object obj = ResourceManager.GetObject("Attuned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;displayName&quot;: &quot;Accuracy&quot;,
        ///    &quot;description&quot;: &quot;Enhances accuracy by {Boost.Attrib.Accuracy.Scale}%.&quot;,
        ///    &quot;attribMods&quot;: [
        ///      [
        ///        {
        ///          &quot;name&quot;: &quot;Accuracy&quot;,
        ///          &quot;table&quot;: &quot;Melee_Boosts_33&quot;,
        ///          &quot;attrib&quot;: &quot;kAccuracy&quot;,
        ///          &quot;scale&quot;: &quot;1.0000&quot;
        ///        }
        ///      ],
        ///      [
        ///        {
        ///          &quot;name&quot;: &quot;Accuracy&quot;,
        ///          &quot;table&quot;: &quot;Melee_Boosts_33&quot;,
        ///          &quot;attrib&quot;: &quot;kAccuracy&quot;,
        ///          &quot;scale&quot;: &quot;0.6250&quot;
        ///        }
        ///      ],
        ///      [
        ///        {
        ///          &quot;name&quot;: &quot;Accuracy&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoostTypes {
            get {
                return ResourceManager.GetString("BoostTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;AutoSave&quot;:true}
        ///.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crafted {
            get {
                object obj = ResourceManager.GetObject("Crafted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  0,
        ///  0,
        ///  0,
        ///  0,
        ///  0,
        ///  0,
        ///  0,
        ///  0,
        ///  0,
        ///  3600,
        ///  4380,
        ///  5160,
        ///  5940,
        ///  6720,
        ///  7500,
        ///  12900,
        ///  18300,
        ///  23700,
        ///  29100,
        ///  34500,
        ///  35080,
        ///  35660,
        ///  36240,
        ///  36820,
        ///  37400,
        ///  38660,
        ///  39920,
        ///  41180,
        ///  42440,
        ///  43700,
        ///  48200,
        ///  52700,
        ///  57200,
        ///  61700,
        ///  66200,
        ///  73920,
        ///  81640,
        ///  89360,
        ///  97080,
        ///  104800,
        ///  121260,
        ///  137720,
        ///  154180,
        ///  170640,
        ///  187100,
        ///  198720,
        ///  210340,
        ///  221960,
        ///  233580,
        ///  490400
        ///]
        ///.
        /// </summary>
        internal static string CraftingCost {
            get {
                return ResourceManager.GetString("CraftingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kBuff_Defense_Boost {
            get {
                object obj = ResourceManager.GetObject("kBuff_Defense_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kBuff_ToHit_Boost {
            get {
                object obj = ResourceManager.GetObject("kBuff_ToHit_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kConfuse_Boost {
            get {
                object obj = ResourceManager.GetObject("kConfuse_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kDamage_Boost {
            get {
                object obj = ResourceManager.GetObject("kDamage_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kDebuff_Defense_Boost {
            get {
                object obj = ResourceManager.GetObject("kDebuff_Defense_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kDebuff_ToHit_Boost {
            get {
                object obj = ResourceManager.GetObject("kDebuff_ToHit_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kFear_Boost {
            get {
                object obj = ResourceManager.GetObject("kFear_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kHeal_Boost {
            get {
                object obj = ResourceManager.GetObject("kHeal_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kHold_Boost {
            get {
                object obj = ResourceManager.GetObject("kHold_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kImmobilized_Boost {
            get {
                object obj = ResourceManager.GetObject("kImmobilized_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kJump_Boost {
            get {
                object obj = ResourceManager.GetObject("kJump_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kKnockback_Boost {
            get {
                object obj = ResourceManager.GetObject("kKnockback_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kRange_Boost {
            get {
                object obj = ResourceManager.GetObject("kRange_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kRecovery_Boost {
            get {
                object obj = ResourceManager.GetObject("kRecovery_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kRes_Damage_Boost {
            get {
                object obj = ResourceManager.GetObject("kRes_Damage_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kSleep_Boost {
            get {
                object obj = ResourceManager.GetObject("kSleep_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kSlow_Boost {
            get {
                object obj = ResourceManager.GetObject("kSlow_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kSpeedFlying_Boost {
            get {
                object obj = ResourceManager.GetObject("kSpeedFlying_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kSpeedRunning_Boost {
            get {
                object obj = ResourceManager.GetObject("kSpeedRunning_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kStunned_Boost {
            get {
                object obj = ResourceManager.GetObject("kStunned_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kTaunt_Boost {
            get {
                object obj = ResourceManager.GetObject("kTaunt_Boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Recipe {
            get {
                object obj = ResourceManager.GetObject("Recipe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;displayName&quot;: &quot;Accurate Defense Debuff&quot;,
        ///    &quot;groupName&quot;: &quot;P1905706306&quot;,
        ///    &quot;boostsAllowed&quot;: &quot;kDebuff_Defense_Boost&quot;,
        ///    &quot;conversionGroup&quot;: &quot;ECAccurateDefenseDebuff&quot;,
        ///    &quot;include&quot;: &quot;Accurate_Defense_Debuff_Powers&quot;
        ///  },
        ///  {
        ///    &quot;displayName&quot;: &quot;Accurate Healing&quot;,
        ///    &quot;groupName&quot;: &quot;P500425294&quot;,
        ///    &quot;boostsAllowed&quot;: &quot;kHeal_Boost&quot;,
        ///    &quot;conversionGroup&quot;: &quot;ECAccurateHealing&quot;,
        ///    &quot;include&quot;: &quot;Accurate_Healing_Powers&quot;
        ///  },
        ///  {
        ///    &quot;displayName&quot;: &quot;Accurate To-Hit Debuff&quot;,
        ///    &quot;groupNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetGroups {
            get {
                return ResourceManager.GetString("SetGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Superior {
            get {
                object obj = ResourceManager.GetObject("Superior", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
